server:
  port: 8181

spring:
  datasource:
    name: main
    url: jdbc:mysql://127.0.0.1:3306/db_habit?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      filters: stat
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 'x'
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 300000
      time-between-connect-error-millis: 60000