spring:
  profiles:
#    active: dev
    active: prod
  http:
    encoding:
      charset: utf-8
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

server:
  servlet:
    context-path: /habit