spring:
  profiles:
#    active: dev
    active: prod
  http:
    encoding:
      charset: utf-8
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

server:
  servlet:
    context-path: /habit

# 该配置节点为独立的节点，放在spring的节点下会导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/*.xml       # 对应mapper映射xml文件的所在路径
  type-aliases-package: com.kowah.habitapp.bean    # 对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql